import Mathlib.Analysis.Calculus.LocalExtr.Basic

/-!
# Fermat's theorem for one-sided derivatives on the real line

`IsLocalMinOn.hasFDerivWithinAt_nonneg` signs a derivative within a set against the positive
tangent cone of that set.  On the real line the positive tangent cones of the two half-lines
at `a` are generated by `1` and by `-1`, which turns that statement into the two familiar
one-sided derivative tests at a one-sided minimum.
-/

/-- The forward direction belongs to the positive tangent cone of a right half-line. -/
theorem one_mem_posTangentConeAt_Ici (a : ℝ) : (1 : ℝ) ∈ posTangentConeAt (Set.Ici a) a :=
  mem_posTangentConeAt_of_segment_subset
    ((convex_Ici a).segment_subset (Set.mem_Ici.2 le_rfl) (Set.mem_Ici.2 (by linarith)))

/-- The backward direction belongs to the positive tangent cone of a left half-line. -/
theorem neg_one_mem_posTangentConeAt_Iic (a : ℝ) :
    (-1 : ℝ) ∈ posTangentConeAt (Set.Iic a) a :=
  mem_posTangentConeAt_of_segment_subset
    ((convex_Iic a).segment_subset (Set.mem_Iic.2 le_rfl) (Set.mem_Iic.2 (by linarith)))

/-- A right derivative at a minimum over a right half-line is nonnegative. -/
theorem IsLocalMinOn.hasDerivWithinAt_Ici_nonneg {f : ℝ → ℝ} {f' a : ℝ}
    (h : IsLocalMinOn f (Set.Ici a) a) (hf : HasDerivWithinAt f f' (Set.Ici a) a) : 0 ≤ f' := by
  simpa using h.hasFDerivWithinAt_nonneg hf (one_mem_posTangentConeAt_Ici a)

/-- A left derivative at a minimum over a left half-line is nonpositive. -/
theorem IsLocalMinOn.hasDerivWithinAt_Iic_nonpos {f : ℝ → ℝ} {f' a : ℝ}
    (h : IsLocalMinOn f (Set.Iic a) a) (hf : HasDerivWithinAt f f' (Set.Iic a) a) : f' ≤ 0 :=
  neg_nonneg.1 <| by
    simpa using h.hasFDerivWithinAt_nonneg hf (neg_one_mem_posTangentConeAt_Iic a)
